import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ECF9F6',
    alignItems: 'center',
    paddingTop: 30,
  },
  header: {
    fontSize: 17,
    fontWeight: '600',
    color: '#222',
    textAlign: 'center',
    marginBottom: 32,
    marginTop: 128,
  },
  card: {
    width: '88%',
    backgroundColor: '#fff',
    borderRadius: 18,
    alignItems: 'center',
    paddingVertical: 32,
    paddingHorizontal: 15,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 8,
    elevation: 2,
    marginTop:10,
  },
  iconWrapper: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 2,
    borderColor: '#2DEB89',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 22,
    backgroundColor: '#ECF9F6',
  },
  badgeImage: {
    width: 77,
    height: 77,
    borderRadius: 38.5,
  },
  levelCompleted: {
    fontSize: 15,
    color: '#777',
    marginBottom: 6,
    marginTop: 4,
    textAlign: 'center',
  },
  badgeTitle: {
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 3,
    color: '#212121',
    textAlign: 'center',
  },
  exp: {
    fontSize: 13,
    color: '#26b46b',
    marginBottom: 18,
    textAlign: 'center',
  },
  claimButton: {
    width: '95%',
    backgroundColor: '#1794A6',
    borderRadius: 7,
    paddingVertical: 10,
    marginTop: 2,
    marginBottom: 13,
  },
  claimButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  shareRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  shareIcon: {
    fontSize: 18,
    marginRight: 7,
    color: '#555',
  },
  shareText: {
    color: '#555',
    fontSize: 15,
  },
});
