import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCF9',
    paddingTop: 12,
  },
  header: {
    color: '#C5C5C5',
    fontWeight: '600',
    fontSize: 16,
    marginLeft: 18,
    marginBottom: 10,
    marginTop: 6,
  },
  contentWrapper: {
    flex: 1,
    alignItems: 'center',
    height:15,
    justifyContent: 'center',
  },
  card: {
    width: '90%',
    height: 480,
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 32,
    paddingHorizontal: 18,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 6,
  },
  gamePreview: {
    width: '100%',
    height: 150,
    backgroundColor: '#E2E2E2',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 32,
  },
  previewText: {
    color: '#555',
    fontSize: 13,
    marginTop:6,
    textAlign: 'center',
  },
  title: {
    fontWeight: 'bold',
    fontSize: 16,
    marginTop:16,
    textAlign: 'center',
    marginBottom: 18,
    color: '#1A1A1A',
  },
  description: {
    color: '#6A6A6A',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 44,
    marginTop:15,
  },
  button: {
    width: '100%',
    backgroundColor: '#000',
    borderRadius: 10,
    paddingVertical: 12,
    marginTop: 6,
  },
  buttonText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 16,
  },
});
